name: Daily DB Reset
on:
  schedule:
    - cron: "0 0 * * *" #midnight
  workflow_dispatch: #works manually too

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Reset and seed database
        run: |
          npx prisma db push --force-reset --accept-data-loss
          npx prisma db seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
